version: '3'

services:
  app:
    build:
      context: .
    container_name: tyba_app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app  
      - 'tyba:/app/node_modules'

  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: tyba_db
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  tyba:

